phoenix_logo:
    title: Phoenix Logo
    description: The logo for the Phoenix project with the text Phoenix by Connective DX

phoenix_logoonly:
    title: Phoenix Logo Only
    description: Just the logo for the Phoenix project
